from itertools import product

ALLOWED_SUITS = ['H','D','C','S']
ALLOWED_NUMBERS = [i for i in range(1,14)]
ALLOWED_CARDS = list(product(ALLOWED_NUMBERS,ALLOWED_SUITS))

HAND_HIERARCHY_MAP = {'ROYAL FLUSH': 1, 'STRAIGHT FLUSH': 2, 'FOUR OF A KIND': 3, 'FULL HOUSE': 4, 'FLUSH': 5, 'STRAIGHT': 6, 'THREE OF A KIND': 7, 'TWO PAIR': 8, 'PAIR': 9, 'HIGH CARD': 10}


